version: 1.0.{build}

build:
  verbosity: minimal

test:
  assemblies: '**\bin\Debug\SomeTools.Tests.dll'

artifacts:
- path: '**\bin\Debug\*'
  name: Files

deploy:
  provider: NuGet
  api_key:
    secure: 3JSVyqTNWRcvMXqrpmKghpgoRKTFmU0hKV2vuGQ+sK+rUawCCpMh7Ykd2PpzH9uc
  artifact: /.*\.nupkg/