version: 1.0.{build}

assembly_info:
  patch: true
  file: SomeTools\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

build:
  publish_nuget: true
  verbosity: minimal

test:
  assemblies: 'SomeTools.Tests\bin\Debug\SomeTools.Tests.dll'

artifacts:
- path: 'SomeTools\bin\Debug\*'
  name: Files
- path: '**\*.nupkg'
  name: Package

deploy:
  provider: NuGet
  api_key:
    secure: 3JSVyqTNWRcvMXqrpmKghpgoRKTFmU0hKV2vuGQ+sK+rUawCCpMh7Ykd2PpzH9uc
  artifact: /.*\.nupkg/
  on:
    branch: master